### ISSUE TITLE
bridge ogms-discuss and github issues

### ISSUE THREAD

**Issue by alanruttenberg** [OGMS/ogms#101]
Here's a way I tried and it seemed to work:

Settings for ogms-discuss:
- Allow public posting, settings: moderate public posts, don’t send an email when a message is rejected.
- Create github user with group email address
- Confirm email in google group then delete message
- Add (2) to repo
- Accept invitation in google group then delete message
- Logged in as (2) watch issues
- Submit a test issue
- In the moderation queue select the message and choose allow post now and in future (you need to permit posting this way as google won’t let you add notifications@github.com as member of group

Now it should be the case that whether you respond from email to github or to google group message (reply all) it should register in the issue and also be mirrored in the google group.

I don’t know if posting from the google groups web interface will work.

**Comment by BAevermann** [comment]
I think we have successfully moved to Github. We have google drives for sharing development materials, and all releases/issue tracking is now on Github.
