### ISSUE TITLE
Revisions to ‘relapse’ and ‘remission’

### ISSUE THREAD

**Issue by mark-jensen** [OGMS/ogms#104]
Discussed during developers’ call on 17 Feb 2016.

Currently (all subclasses of `process`):

[`relapse`](http://purl.obolibrary.org/obo/OGMS_0000105) = a part of a disease course that occurs after an incomplete remission and that is similar to earlier parts of the disease course
[`remission`](http://purl.obolibrary.org/obo/OGMS_0000106) =  a temporary convalescence typically associated with a chronic disease course
[`convalescence`](http://purl.obolibrary.org/obo/OGMS_0000091) = a processual entity during which a patient participating in a disease course gradually returns to participating in a canonical life course. 

Proposal:
OGMS will take control of OBI [`disease stage`](http://purl.obolibrary.org/obo/OBI_0000278), maintaining the IRI. A different issue (forthcoming) will discuss redefining it as a temporal part of a `disease course`.

Make both subclasses of `disease stage`, revising as follows.

`relapse` = a disease stage which is preceded by a remission and characterized by the return of a clinical manifestation of some disease.

`remission` = a disease stage which is characterized by the lack of a clinical manifestation of some disease.

TO DO: provide examples of usage, comment about varying criteria (sometimes fiat) between disease types or individual patients in determining if in remission, consider adding `partial remission`.

**Comment by wdduncan** [comment]
Thanks for proposing these definitions Mark. Yes, the term 'disease stage'
will have to be redefined to make your proposal work. The definitions for
'relapse' and 'remission' both refer to clinical manifestations. This makes
a little worried that we will get ourselves into a tail spin trying to pin
down what a clinical manifestation is.

I offer the following proposal for defining 'relapse' and 'remission'
centered around clinical findings that designate whether a disease has the
status of being in relapse or remission:

*relapse finding* =df a clinical finding that a previous occurrence of
disease has returned (i.e., is being realized) after a period in which the
disease was not present (i.e., not being realized)

*remission finding* =df a clinical finding that a disease is not being
realized

We can then define the remission/relapse parts of disease course in this
way:

*is referent of* =df inverse of is about

*relapse* =df a temporal part a disease course that is the referent of a
relapse finding

*remission* =df a temporal part of a disease course that is the referent of
a remission finding

Many of you (I suspect) will not like my proposal. I can already hear the
criticisms .....
But, I only ask that you give it some thought. From a practical standpoint,
I need to be able for query for things like:

1. patients that took some drug and are currently in remission from some
form of cancer
2. patients who were in remission from some from of cancer but now have
relapsed

The most direct route I see to doing this is by querying based on the
clinical findings about the status of patient's cancer.

Hopefully, this is food for thought.

Bill

**Comment by mark-jensen** [comment]
During the developers call on March 16, it was decided to remove ‘clinical’ from the definitions since it is potentially too restrictive. The proposed definitions become:

`relapse` = a disease stage which is preceded by a remission and characterized by the return of a manifestation of a disease.

`remission` = a disease stage which is characterized by the lack of a manifestation of a disease.

@wdduncan Thanks for the comments. 

> The definitions for 'relapse' and 'remission' both refer to clinical manifestations. This makes a little worried that we will get ourselves into a tail spin trying to pin down what a clinical manifestation is.

I agree that [`manifestation of a disease`](http://purl.obolibrary.org/obo/OGMS_0000022) (clinical or otherwise) may need refinement. Previous [discussion](https://groups.google.com/forum/#!topic/ogms-discuss/P4RG6yATehE/overview) raises the point it may be better represented disjunctively---quality or process or disorder. Others noted it’s epistemic nature and that maybe it shouldn't be a class at all. But, I believe its use, whether as a class or primitive, is warranted here.

>relapse =df a temporal part a disease course that is the referent of a relapse finding
remission =df a temporal part of a disease course that is the referent of a remission finding

This appears to require that any instance of a `relapse` or `remission` necessarily depends on having been observed and recorded. In applications, for particular patients with particular disease, *relapse* and *remission* are certainly very tightly linked to findings. However, I believe that for the domain level of OGMS, it is best not to rely on information artifacts to define them.

**Comment by wdduncan** [comment]
I agree that manifestation of a disease
<http://purl.obolibrary.org/obo/OGMS_0000022> (clinical or otherwise) may
need refinement. Previous discussion
<https://groups.google.com/forum/#!topic/ogms-discuss/P4RG6yATehE/overview>
raises
the point it may be better represented disjunctively---quality or process
or disorder. Others noted it’s epistemic nature and that maybe it shouldn't
be a class at all. But, I believe its use, whether as a class or primitive,
is warranted here.

relapse =df a temporal part a disease course that is the referent of a
relapse finding
remission =df a temporal part of a disease course that is the referent of a
remission finding

This appears to require that any instance of a relapse or remission necessarily
depends on having been observed and recorded. In applications, for
particular patients with particular disease, *relapse* and *remission* are
certainly very tightly linked to findings. However, I believe that for the
domain level of OGMS, it is best not to rely on information artifacts to
define them.


Comment/Question: I agree that the profile (for lack of a better word) is
something that occurs whether or not it is observed by a health provider.
But when do we use the terms "remission" or "relapse" outside of the
relapse/remission being diagnosed by such a provider? Also, I'm not sure
why this falls out of the domain level of OGMS.


Bill

**Comment by sivaramarabandi** [comment]
Agree with Bill, and for the upcoming meeting I am preparing some
definitions for Symptoms, signs, manifestations, clinical findings - we can
see if it will help clarify some of these items.

Couple of tweaks to the definitions:

relapse = a disease stage which is preceded by a remission and
characterized by the return of one or more manifestations of the disease.

remission = a disease stage which is characterized by a reduction in the
manifestations of a disease.
    - in its usage, the word remission suggests that the the disease is not
cured, and can come back.
    - to say a disease is in remission, (usually) more than one
manifestation of the disease must reduce - hence the use of plural form
'manifestations'.

thanks
Sivaram


______________________
Sivaram Arabandi, MD, MS

ONTOPRO
W:  http://ontopro.com/
Ph: 832.726.2322

**Comment by wdduncan** [comment]
My main concern is how remission/relapse will be implemented for actual
patients. For example, being in remission for cancer, MS, and HIV will all
mean different disjoint things. Thus, remission from cancer is a very
different thing than remission from MS, and both are very different that
remission from HIV (and so on). This makes me doubt there is a universal
'disease remission' (and also 'disease manifestation').

Your right, perhaps we can make disjunctive classes
'remission'/'manifestation', but I'd like to see how these classes will be
defined. We can also just not have the classes 'remission'/'manifestation'
defined in the ontology and let our intuitions work with the textual
definitions.

Finally, perhaps some use cases might be helpful. Here is one:

patient A has tumor in her left breast on date #2
patient A has tumor removed and undergoes chemotherapy between dates date
#3 - date #4
patient does not have any tumors in her breast on date #5
patient A has tumor (derived from original tumor in left breast) in her
right breast on date #6

On date #5, patient A is in remission, and on date #6 she has a
recurrence/relapse. Could you lay out how this would be represented in the
current proposal and contrast it with remission/relapse in an MS patient?

Bill

**Comment by mark-jensen** [comment]
Terms added in 9bd4621 & 8b72dc7.
