### ISSUE TITLE
NTR: "clinical data item"

### ISSUE THREAD

**Issue by johnwjudkins** [OGMS/ogms#124]
This is for the EuPathDB project and the ClinEpiDB site. The parent would be "data item". Definition: "a data item that is about a patient and is the specified output of a health care process assay or diagnostic process". EuPath needs a class to cover data items like the following:
amebiasis
asymptomatic
atypical mycobacterium infection, COPD, CCPA and aspergilloma
bloodstream infection
cutaneous leishmaniasis
diarrhea
enterocolitis, diarrhea and cholangiopathy
healthy
HIV infected
hospital acquired infection
Infected With Malaria
malaria
nodular infiltrate in a corticosteroid-treated patient
sarcoidosis and bilateral large aspergillomas
sarcoidosis, CCPA, and bilateral aspergilloma
symptomatic
Symptomatic episode
uninfected with malaria
vaginitis
visceral leishmaniasis

**Comment by cstoeckert** [comment]
@scheuerm can this be discussed? Thanks, Chris

**Comment by BAevermann** [comment]
@cstoeckert, @johnwjudkins 
We will be having a development call this Wednesday the 16th of Jan. If you can make it, please let me know and we can open discussion.

Thanks,

Brian A.

**Comment by johnwjudkins** [comment]
I’ll be there. Thanks.

**Comment by BAevermann** [comment]
Added clinical data item and moved diagnosis as a child. In addition, clinical finding was made a child.
