### ISSUE TITLE
New term request: county smoking survey plan specification; county smoking survey execution; county smoking survey data

### ISSUE THREAD

**Issue by CDowland** [OGMS/ogms#143]
**First term:**

Editor preferred term: county smoking survey plan specification
Textual definition: A survey plan specification that aims to collect information about the smoking behavior or lack thereof of a population on a county level. Concretization of a smoking survey plan that is stratified by county.
Logical definition or parent term: survey plan specification
Example of usage: The Alachua county smoking survey plan specification.
Term editor: Mathias Brochhausen
Contributor(s): Hansi Zhang, Jiang Bian, S. Clint Dowland, Matthew Diller, William R. Hogan, Sarah Bost

**Second term:**

Editor preferred term: county smoking survey execution
Textual definition: A survey execution that realizes the concretization of a smoking survey plan specification that is stratified by county.
Logical definition or parent term: survey execution; realizes some (concretizes some county smoking survey plan specification) (equivalent class)
Example of usage: The Alachua county smoking survey execution.
Term editor: Mathias Brochhausen
Contributor(s): Hansi Zhang, Jiang Bian, S. Clint Dowland, Matthew Diller, William R. Hogan, Sarah Bost

**Third term:**

Editor preferred term: county smoking survey data
Textual definition: Survey data that is the specified output of a county smoking survey execution.
Logical definition or parent term: survey data (OMIABIS, OBIB); is_specified_output_of some county smoking survey execution (equivalent class)
Example of usage: The Alachua county smoking survey data.
Term editor: Mathias Brochhausen
Contributor(s): Hansi Zhang, Jiang Bian, S. Clint Dowland, Matthew Diller, William R. Hogan, Sarah Bost

**Related request:**

In conjunction with the requests for three county smoking survey-related terms, we also request that the following terms be imported via MIREOT or some other method:

- ‘survey data’ (OMIABIS, OBIB)
- ‘survey execution’ (OMIABIS, OBIB) 
-  ‘survey plan specification’ (OMIABIS, OBIB)

The reason for this additional request is that the above terms are the intended parent classes of the county smoking survey-related terms, and are used in their logical definitions. 
[county-smoking-term-requests-20200625.xlsx](https://github.com/OGMS/ogms/files/4974381/county-smoking-term-requests-20200625.xlsx)

**Comment by BAevermann** [comment]
Possibly out of scope. Tabling discussion until other terms decided upon...

**Comment by sjbost** [comment]
Since it sounded like this wasn't a good fit for OGMS, we implemented these and two other affiliated terms in OMRSE: 

'county smoking survey plan specification', 'county smoking survey execution', and 'county smoking survey data': https://github.com/ufbmi/OMRSE/commit/72a50f993f75357e52a82d844004dbbe5363f870
'county smoking rate data' and 'smoking rate calculation': https://github.com/ufbmi/OMRSE/commit/c199a94c6412a0df5b317e52a94a0c9a6196b890

This issue can be closed.

**Comment by BAevermann** [comment]
Closed as terms were added to OMRSE. Thanks @sjbost
