### ISSUE TITLE
Problematic annotation property in OWL file

### ISSUE THREAD

**Issue by beckyjackson** [OGMS/ogms#144]
In the version of OGMS at http://purl.obolibrary.org/obo/ogms.owl, it appears there is an annotation property with a space in the IRI:
```
http://www.w3.org/2002/07/owl#versionIRI rdf:resource
```

This opens fine in Protege, but spaces shouldn't be used in IRIs and this causes problems when parsing the file with other tools.

**Comment by BAevermann** [comment]
Resolved in latest release
