### ISSUE TITLE
Invalid values in xml:lang attributes

### ISSUE THREAD

**Issue by jvendetti** [OGMS/ogms#145]
There are two occurrences in ogms.owl where the xml:lang attributes contain invalid values:

1. A dc:description on [line 33](https://github.com/OGMS/ogms/blob/6ff46780d05fe1ed873f24b679a1b32a87bf0c5b/src/ontology/ogms.owl#L33).

2. An rdfs:comment on [line 39](https://github.com/OGMS/ogms/blob/6ff46780d05fe1ed873f24b679a1b32a87bf0c5b/src/ontology/ogms.owl#L39).

In other words, there is this:

`<rdfs:comment xml:lang="jcvi.org. be sure to include a google-account username with your request (this will be the username associated with a gmail address). we use google apps for sharing and development purposes.">`

... instead of this:

`<rdfs:comment xml:lang="en">`

These xml:lang attributes with invalid values prevent ogms from loading properly in BioPortal, e.g., see this page with an error status in the Submissions table:

http://bioportal.bioontology.org/ontologies/OGMS

... and it also prevents ontologies from loading properly that are importing ogms, e.g., [PDRO](http://bioportal.bioontology.org/ontologies/PDRO).

**Comment by BAevermann** [comment]
Resolved in latest release
