### ISSUE TITLE
term request: congenital

### ISSUE THREAD

**Issue by rvita** [OGMS/ogms#149]
Hi, we would like to be able to use the concept of 'congenital' outside of the existing OGMS term
congenital malformation http://purl.obolibrary.org/obo/OGMS_0000089
as in the situation with congenital infections, for example. We'd like to use it as an indication of the setting of where/how a disease was acquire, regardless of what the disease is.
This is for clinical RedCap patient intake forms. Thanks

**Comment by BAevermann** [comment]
added terms in version v2021-04-20
-congenital process
-congenital infection
-drug induced congenital malformation
