### ISSUE TITLE
new term: recurrent

### ISSUE THREAD

**Issue by rvita** [OGMS/ogms#150]
Hi, "recurrent" exists in several other ontologies, but should this not be in OGMS? Can you review these terms and decide if it is within your scope?
http://purl.obolibrary.org/obo/NCIT_C14173
http://purl.obolibrary.org/obo/HP_0031796
http://www.ebi.ac.uk/efo/EFO_0010246 
Thanks
--

**Comment by BAevermann** [comment]
add synonym recurrent to 
http://purl.obolibrary.org/obo/OGMS_0000105
--
