### ISSUE TITLE
Nosocomial infection 

### ISSUE THREAD

**Issue by BAevermann** [OGMS/ogms#152]
add term

**Comment by BAevermann** [comment]
See IDO

Parent: infection (add to OGMS?)
http://purl.obolibrary.org/obo/IDO_0000586
--

hospital-acquired infection:

http://purl.obolibrary.org/obo/IDO_0000630
--

**Comment by PhiBabs935** [comment]
I should note that the Ontobee site still reflects an older version of IDO that predates various 2020 updates that I and others worked on (changed reflected in the recent IDO preprint paper). The most recent uploaded version is on Bioportal (though, more recently revised versions are coming). Not sure why the Ontobee team never updated our newer version on their site.

**Comment by yongqunh** [comment]
We have double checked. The IDO PURL link:
http://purl.obolibrary.org/obo/ido.owl
 
appears to link to the following URL: 
https://raw.githubusercontent.com/infectious-disease-ontology/infectious-disease-ontology/2017-11-03/ido.owl
This is the 2017 version. 
 
To solve this, the link setup needs to be updated first. This can be done by sending a request to OBO foundry.

**Comment by BAevermann** [comment]
added IDO term to OGMS
