### ISSUE TITLE
Better to have merged ogms owl version

### ISSUE THREAD

**Issue by yongqunh** [OGMS/ogms#163]
It would be better to have a final merged ogms owl version rather than unmerged version.

Somehow Ontobee updating script has always some issue in updating OGMS updated owl version to Ontobee:
http://www.ontobee.org/ontology/OGMS

Thanks, Oliver

**Comment by BAevermann** [comment]
Current version should be merged. Thanks for the suggestion.

b.

**Comment by yongqunh** [comment]
Yes. That's great. Thanks!
