### ISSUE TITLE
The OGMS PURL is broken

### ISSUE THREAD

**Issue by hoganwr** [OGMS/ogms#166]
The PURL http://purl.obolibrary.org/obo/ogms.owl redirects to a GitHub 404

https://raw.githubusercontent.com/OGMS/ogms/master/src/ontology/ogms.owl

The file is instead currently at:

https://raw.githubusercontent.com/OGMS/ogms/master/ogms.owl

**Comment by alanruttenberg** [comment]
Should be able to fix it here: https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/ogms.yml

**Comment by BAevermann** [comment]
Hey Dr Hogan!
Was the PURL link above (in the first line) that redirects to 404? At current it goes to a version of OGMS (not sure which one though).

The second URL does lead to a 404.

Just want to make sure I dont break things while trying to fix them.
 
Thanks,

b.

**Comment by hoganwr** [comment]
Brian,

I believe Nico and James took care of this issue.

Bill

**Comment by BAevermann** [comment]
Oh Great! Thanks!
