### ISSUE TITLE
Proposed term 'Organism Population'

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OGMS/ogms#33]
```
Organism Population: Aggregate of organisms of the same type.

Comment: Usually specified by spatiotemporal or demographic criteria. 

```

Original issue reported on code.google.com by `albertgo...@gmail.com` on 30 Sep 2009 at 2:18

**Comment by zhengj2007** [comment]
The terms have been covered by Population and Community Ontology (PCO).

Please check 'collection of organisms' and its subclasses:
http://purl.obolibrary.org/obo/PCO_0000000

**Comment by linikujp** [comment]
This URI direct to the google code and the browser shows '404 not found'.

**Comment by linikujp** [comment]
I will try to update the PURLS asap and post here when it it done.

------------------------------------------------------
Ramona L. Walls, Ph.D.
Scientific Analyst, The iPlant Collaborative, University of Arizona
Research Associate, Bio5 Institute, University of Arizona
Laboratory Research Associate, New York Botanical Garden

**Comment by zhengj2007** [comment]
The PURL redirect to pco.owl is updated. Resolving Term IRI may need to contact Chris M.

**Comment by BAevermann** [comment]
Closed ticket because issues has not been acted upon in reasonable amount of time.
