### ISSUE TITLE
What is the relation that holds between diseases and pathological processes?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OGMS/ogms#42]
```
Perhaps this is an issue for BFO more generally, but what is the relation
that holds between diseases (disposition) and pathological processes (process)?

In other words, how do I link a disease to the pathological process to
which it disposes?

If a disposition may never be realized, then the relation probably should
not point from disposition to process, else the all-some principle is
violated (it is not the case that all instances of disposition are realized
by some process instance).

However, if the relation points from process to disposition, then either
(1) the all-some principle is again violated if one process type is the
realization of multiple disposition types or (2) dispositions are uniquely
defined by the process that realizes them.

I don't remember that BFO has anything to say about it.

```

Original issue reported on code.google.com by `hoga...@gmail.com` on 16 Dec 2009 at 1:48

**Comment by cmungall** [comment]
OBO format does not directly support universals, and hence OE does not either.

But see e.g. capable_of http://purl.obolibrary.org/obo/RO_0002215 - shortcut relation that avoids the intermediate node baggage

**Comment by linikujp** [comment]
Hi Chris,

The relation between disease and pathological process would be an interest
for a lot of people.
Do you have a candidate relation from RO?

Can we say that 'disease' is manifestation of 'pathological process' for a
very simple representation?

Thanks,
Asiyah

**Comment by BAevermann** [comment]
Closed ticket because issue has not been acted upon in reasonable amount of time.
