### ISSUE TITLE
Should treatment be subclass of health care process?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OGMS/ogms#88]
```
Looks like it to me. Ditto:
-clinical history taking
-convalescence
-diagnostic process
-history
-laboratory test
-physical examination
-prophylaxis
-treatment
```

Original issue reported on code.google.com by `alanruttenberg@gmail.com` on 21 Dec 2014 at 4:32

**Comment by BAevermann** [comment]
I believe the debate has been rested and treatment will stay under planned process. We can reopen debate in the future if necessary.
