### ISSUE TITLE
Class request - Death

### ISSUE THREAD

**Issue by aellenhicks** [OGMS/ogms#95]
We propose the following definition of 'death' -  A process boundary that occupies the latest instant occupied by a life course.

**Comment by zhengj2007** [comment]
Does UBERON:death stage meet your needs:
http://purl.obolibrary.org/obo/UBERON_0000071

**Comment by aellenhicks** [comment]
We are looking for something that is modelled as a process boundary to distinguish it from processes that have more than one instant. Unfortunately, 'death stage' seems to be too broad.

**Comment by zhengj2007** [comment]
I think UBERON is the better home for the term. It might be good to submit the term to UBERON and contact UBERON developers for it. It seems UBERON is using BFO 1.1 and processual_entity is the parent of process and 'process boundary'.

**Comment by sbjain** [comment]
test

**Comment by BAevermann** [comment]
Closed ticket because issue has not been acted upon in reasonable amount of time.
