### ISSUE TITLE
OGMS OWL PURLs still point to googlecode.com

### ISSUE THREAD

**Issue by jonathanbona** [OGMS/ogms#96]
The PURLs for the _OWL version_ and the _development version_ of OGMS listed in [the README](https://github.com/OGMS/ogms/blob/master/README.md) still go to 
https://ogms.googlecode.com/svn/releases/2014-06-20/ontology/ogms.owl and 
https://ogms.googlecode.com/svn/trunk/src/ontology/ogms.owl

**Comment by cmungall** [comment]
Blocked on https://github.com/OBOFoundry/OBOFoundry.github.io/issues/159

**Comment by mark-jensen** [comment]
Partially addressed with #108 and https://github.com/OBOFoundry/purl.obolibrary.org/pull/188

Still need to determine the location for the stable current release version of OMGS vs editors/develop version at master/src. Currently the latter version is where the PURL directs to.

**Comment by cmungall** [comment]
Yes, your dev version is pointing to a 404, see: https://github.com/OBOFoundry/OBOFoundry.github.io/issues/467

What's your use case for the dev version? Who uses it?

While I'm here I note you still have a few stale mentions of googlecode:

https://github.com/OGMS/ogms/search?utf8=%E2%9C%93&q=googlecode.com&type=

**Comment by BAevermann** [comment]
This should be fully addressed now. Dev branch is gone and Stable release is on github with appropriate direction (URL).
